#cloud-config
write_files:
  - path: /etc/rabbitmq/enabled_plugins
    content: |
        [rabbitmq_management].
  - path: /root/find_hosts.sh
    content: |
        #!/usr/bin/env bash

        export AWS_DEFAULT_REGION='${region}'

        DNSES=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=rabbitmq-*-${env}" "Name=instance-state-name,Values=running" | jq ".Reservations[].Instances[].PrivateDnsName" | xargs)

        HOSTNAMES=()
        for dns in $DNSES; do
            hostname=`echo $dns | awk -F. '{print $1}'`
            if [ "$dns" != "$HOSTNAME" ]; then
              HOSTNAMES+="$hostname "
            fi
        done

        echo $HOSTNAMES
  - path: /root/bin/join_cluster.sh
    content: |
        #!/usr/bin/env bash

        HOSTNAMES=$@

        for run in {1..3}; do
          sleep $[ ( $RANDOM % 20 )  + 1 ]s
          rabbitmqctl stop_app

          NEW_HOSTNAMES=()
          for hostname in $HOSTNAMES; do
            rabbitmqctl join_cluster rabbit@$hostname
            st=$?
            if [ $st -ne 0 ] && [ $st -ne 130 ]; then  # 130 is "already joined"
              NEW_HOSTNAMES+=( $hostname )
            fi
          done

          HOSTNAMES=( $${NEW_HOSTNAMES[@]} )
          rabbitmqctl start_app

          if [ $${#HOSTNAMES[@]} -eq 0 ]; then
            exit 0
          fi
        done
  - path: /root/configure.sh
    content: |
        #!/usr/bin/env bash
        rabbitmqctl add_user admin ${admin_password}
        rabbitmqctl set_user_tags admin administrator
        rabbitmqctl add_vhost /
        rabbitmqctl set_policy ha-all "^" '{"ha-mode":"all"}'
        rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
        rabbitmqctl delete_user guest

runcmd:
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  - python get-pip.py
  - pip install awscli
  - aws configure set default.region us-east-1
  - yum update -y
  - yum install -y wget epel-release perl
  - yum -y update
  - yum -y install socat jq
  - wget https://github.com/rabbitmq/erlang-rpm/releases/download/v21.1/erlang-21.1-2.el7.centos.x86_64.rpm
  - rpm -Uvh erlang-21.1-2.el7.centos.x86_64.rpm
  - wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.8/rabbitmq-server-3.7.8-1.el7.noarch.rpm
  - rpm --import https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.8/rabbitmq-server-3.7.8-1.el7.noarch.rpm.asc
  - rpm -Uvh rabbitmq-server-3.7.8-1.el7.noarch.rpm
  - echo ${secret_cookie} > /var/lib/rabbitmq/.erlang.cookie
  - chmod 600 /var/lib/rabbitmq/.erlang.cookie
  - systemctl start rabbitmq-server
  - systemctl enable rabbitmq-server
  - rabbitmq-plugins enable rabbitmq_management
  - chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/
  - sleep 10
  - bash /root/bin/join_cluster.sh $(bash /root/find_hosts.sh)
  - sleep 10
  - bash /root/configure.sh
  - rabbitmqctl set_cluster_name rabbitmq-${env}
  - cp /usr/share/doc/rabbitmq-server-*/rabbitmq.config.example /etc/rabbitmq/rabbitmq.config
  - perl -ni -le 'print; print "   {vm_memory_high_watermark, 0.8}" if /vm_memory_high_watermark, 0.4/' /etc/rabbitmq/rabbitmq.config
  - perl -ni -le 'print; print "   {loopback_users, \[\]}," if /loopback_users, \[\]/' /etc/rabbitmq/rabbitmq.config
  - systemctl restart rabbitmq-server
